import Link from "next/link";
import "../globals.css";
import { getPages } from "@/sanity/sanity-utils";
import Nav from "./Components/Nav";


export const metadata = {
  title: "My first next app",
  description: "Generated by Next + Sanity",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //get all of our pages

  const pages = await getPages();

  return (
      <>
      <Nav></Nav>
      <div className="bg-indigo-600 w-full">
      <div className="max-w-3xl mx-auto py-10">
        <main className="py-20">{children}</main>
      </div>

      
      </div>
      
      </>
  );
}
